site_name: Backstage
site_description: 'Documentation for SKIPs Backstage'
repo_url: https://github.com/kartverket/kartverket.dev
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Kartverket.dev:
      - Felles begreper: 'kartverket-dev/entities.md'
  - Getting Started:
      - Adding your documentation: 'getting-started/techdocs.md'
