name: "Deploy to GCP"

on:
  push:
    paths:
        - "terraform/**"
        - ".github/workflows/terraform.yml"

jobs:
  sandbox:
    name: Deploy to sandbox
    permissions:
      # For logging on to Vault, GCP
      id-token: write
      # For writing comments on PR
      pull-requests: write
      # For fetching git repo
      contents: read
      # For accessing repository
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v4.4.0
    with:
      runner: ubuntu-latest
      environment: sandbox
      terraform_workspace: sandbox
      terraform_option_1: -var-file=sandbox.tfvars
      working_directory: terraform
      auth_project_number: "833464919209"
      service_account: utviklerportal-deploy@utviklerportal-sandbox-5af9.iam.gserviceaccount.com
      project_id: utviklerportal-sandbox-5af9
      use_platform_modules: true
  dev:
    needs: [sandbox]
    name: Deploy to dev
    permissions:
      # For logging on to Vault, GCP
      id-token: write
      # For writing comments on PR
      pull-requests: write
      # For fetching git repo
      contents: read
      # For accessing repository
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v4.4.0
    with:
      runner: ubuntu-latest
      environment: dev
      terraform_workspace: dev
      terraform_option_1: -var-file=dev.tfvars
      working_directory: terraform
      auth_project_number: "984647225311"
      service_account: utviklerportal-deploy@utviklerportal-dev-9dca.iam.gserviceaccount.com
      project_id: utviklerportal-dev-9dca
      use_platform_modules: true
  prod:
    needs: [sandbox, dev]
    name: Deploy to prod
    permissions:
      # For logging on to Vault, GCP
      id-token: write
      # For writing comments on PR
      pull-requests: write
      # For fetching git repo
      contents: read
      # For accessing repository
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v4.4.0
    with:
      runner: ubuntu-latest
      environment: prod
      terraform_workspace: prod
      terraform_option_1: -var-file=prod.tfvars
      working_directory: terraform
      auth_project_number: "208889908729"
      service_account: utviklerportal-deploy@utviklerportal-prod-ba53.iam.gserviceaccount.com
      project_id: utviklerportal-prod-ba53
      use_platform_modules: true

